### ISSUE TITLE
Unable to process images which are received from socketio image buffer

### ISSUE THREAD

**Issue by bhargavravat** [SthPhoenix/InsightFace-REST#18]
hi @SthPhoenix : 

if i run the code on the images which are there on my machine then it is working fine. However  when I am trying to process the image which i receive from the socket connection , I am getting this error :

Will you be able to give me some hint in this case ?

> [TensorRT] ERROR: ../rtSafe/cuda/reformat.cu (925) - Cuda Error in NCHWToNCHHW2: 400 (invalid resource handle)
> [TensorRT] ERROR: FAILED_EXECUTION: std::exception
> [TensorRT] ERROR: ../rtSafe/cuda/reformat.cu (925) - Cuda Error in NCHWToNCHHW2: 400 (invalid resource handle)
> [TensorRT] ERROR: FAILED_EXECUTION: std::exception

Note : 
Before sending it to inference I am following below steps :

```
#Model 
model = FaceAnalysis(max_size=[640, 640], backend_name='trt', det_name='retinaface_mnet025_v1', 
			rec_name='arcface_r100_v1',max_rec_batch_size=64)

#here i recv the image
recvdImg  =  data.get("frame")

#to numpy array
nparr = np.frombuffer(recvdImg,dtype=np.uint8,offset=1)

#decoding the image
img_np = cv2.imdecode(nparr,-1)

# doing inferece :
faces = model.get(img_np)
```

**Comment by bhargavravat** [comment]
By reading few blogs I found that this error has something to do with cuda context and this can be solved by 

cuda_ctx=pycuda.autoinit.context .

however I am not able to modify this thing in your source code. Can you please help me with it ?

**Comment by SthPhoenix** [comment]
Could you please provide more info on how image is sent and received?

**Comment by bhargavravat** [comment]
I am connected to a server !

Server is sending me an image in byte array format.

Then I am converting that byte array into numpy array and then processing it further. 

I am only receiving image , not sending!

**Comment by SthPhoenix** [comment]
It's hard to tell which reason might cause this exception without additional info, but I think it's mostly connected to the way you read the image before feeding it for inference.
I have tested this code with reading images from rabbitmq query, and from fastapi endpoint, which is default behavior of this project, and haven't got such exceptions.
If you could provide minimal reproducible example I could try checking it.

**Comment by bhargavravat** [comment]
Here is the reproducible code : 



`from modules.face_model import FaceAnalysis
import logging
import cv2
import time
import os
import pickle
import time
import pickle
import numpy as np
import os
import argparse
import sys
import time
import base64
import socketio
import json
from PIL import Image
from io import StringIO
import pycuda
import pycuda.driver as cuda
import pycuda.autoinit

from pathlib import Path



#Loading Detector and Recognition Model

model = FaceAnalysis(max_size=[640, 640], backend_name='trt', det_name='retinaface_mnet025_v1', 
			rec_name='arcface_r100_v1',max_rec_batch_size=64)


print ("DEBUG 1")
'''
Plugin Variables
'''

PlugName = "Face"
PlugKey = "Face123123"
HostServer = "http://192.168.0.3:9090"

'''
Socker IO Connection  with Reconnection 
'''

sio = socketio.Client(reconnection=True,reconnection_attempts=1000000,ssl_verify = False)
sio.connect(HostServer,transports='websocket')


#Socket IO Connection Event , Built in Reconneciton Logic

@sio.event
def connect():
	print('connection established :==============>')
	sio.emit('ocv', 
{'f':'init','plug':PlugName,'type':'detector','connectionType':'websocket','pluginKey':PlugKey})

#Socket IO Re Connection Event

@sio.event
def reconnect():
	print ("Reconnection established : ==============>")
	sio.emit('ocv', 
{'f':'init','plug':PlugName,'type':'detector','connectionType':'websocket','pluginKey':PlugKey})

#Socket IO Disconnect Event
@sio.event
def disconnect():
	print('disconnected from server')



# Real time data will be recived by this function
@sio.event
def f(data):
    print ("on_f")
    print ("type(data)",type(data))
    shinobiId =  data.get("id")
    shonibiKe =  data.get("ke")
    recvdImg  =  data.get("frame")
    #print ("recvdImg",recvdImg)
    # print ("type of recvdImg", type(recvdImg))  
    nparr = np.frombuffer(recvdImg,dtype=np.uint8,offset=1)
    # print (nparr)
    img_np = cv2.imdecode(nparr,-1)
    # print (img_np)
    #EROOR HERE
    faces = model(img_np)
    
 
# It will wait for socket io events!!
sio.wait()
`

**Comment by bhargavravat** [comment]
[trt_plugin_git.txt](https://github.com/SthPhoenix/InsightFace-REST/files/5866583/trt_plugin_git.txt)


Thanks for the response!
Attached is the reproducible source code for your reference.

**Comment by SthPhoenix** [comment]
Could you also provide minimum server example? For testing full cycle.

**Comment by bhargavravat** [comment]
Yes , image is perfect the way it should be ! 
There is no issues with the input image that's for sure ! I have cross checked with storing that image in local storage and also checked it , it is how it should be !!

**Comment by bhargavravat** [comment]
Here is the server implementation : 


https://gitlab.com/Shinobi-Systems/Shinobi

**Comment by bhargavravat** [comment]
Found the solution!!
Closing it

**Comment by SthPhoenix** [comment]
Great news! Could you please post your solution? I'll apply it to master branch if it doesn't conflict with FastAPI.

**Comment by bhargavravat** [comment]
I have modified trt_loader.py (/app/modules/model_zoo/exec_backends/trt_loader.py)

Attaching it as .txt format

[trt_loader.txt](https://github.com/SthPhoenix/InsightFace-REST/files/5893855/trt_loader.txt)

**Comment by SthPhoenix** [comment]
I have tested your solution with `/src/converters/pipeline_tester.py`, but it fails with following error:
```
PyCUDA ERROR: The context stack was not empty upon module cleanup.
```

I was able to fix it by replacing line 84:
```
self.cuda_ctx = cuda_ctx
```
with:

```
device = cuda.Device(0)  # enter your gpu id here
ctx = device.make_context()
self.cuda_ctx = ctx
```
This worked, but caused excessive GPU RAM usage, about 1GB

**Comment by ThiagoMateo** [comment]
hello @SthPhoenix how to create 1 engine (ex face detection) serve for more than 2 camera using threading?
i tried, but i got confused outputs between these thread.

**Comment by SthPhoenix** [comment]
Hi @ThiagoMateo ! As I have said before, this use case is not tested, for now you can use provided rest API in your application. 
In future versions I'm planning to add full support of Triton Inference Server, which will give you ability to serve single model for multiple threads.
